AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - my.service::jersey-sample
Resources:
  JerseySampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.service.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://adityas3bkt2019/be4e159894fb6ec3731e833204ab6367
      MemorySize: 512
      Policies:
      - AWSLambdaBasicExecutionRole
      - SecretsManagerReadWrite
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          OWAPIKEY: 3ce9069228955f36f223e5bc2406c0a8
Outputs:
  JerseySampleApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping
    Export:
      Name: JerseySampleApi
